# Generated by Django 5.0.3 on 2024-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name_plural': 'Babies'},
        ),
        migrations.AlterModelOptions(
            name='procurement',
            options={'verbose_name_plural': 'Procurement'},
        ),
        migrations.AlterField(
            model_name='sitter',
            name='nin',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
